import { StyleSheet } from 'react-native';
import {
  CUSTOMER_PRIMARY as PRIMARY,
  CUSTOMER_PRIMARY_DARK as PRIMARY_DARK,
  PRICE_KNOB_SIZE,
  PRICE_TRACK_ACTIVE,
  PRICE_TRACK_INACTIVE,
} from '@/src/customer/constants/hotelFilters';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  webContainer: {
    overflow: 'hidden',
  },
  gradientBg: {
    position: 'absolute', top: 0, left: 0, right: 0, height: 220,
    backgroundColor: 'rgba(133,194,164,0.32)',
  },
  webGradientBg: {
    height: 170,
  },
  header: {
    flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16,
    paddingVertical: 10,
  },
  webHeader: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 18,
  },
  backBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  title: { flex: 1, textAlign: 'center', fontSize: 18, fontWeight: '700', color: '#111827' },
  filterPanel: {
    marginHorizontal: 16,
    marginTop: 4,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(133,194,164,0.35)',
    paddingTop: 12,
  },
  webFilterPanel: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    marginHorizontal: 0,
    marginTop: 10,
    marginBottom: 16,
  },
  webResultsLayout: {
    flex: 1,
    width: '100%',
    maxWidth: 1280,
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 18,
    paddingLeft: 32,
    paddingRight: 38,
    paddingTop: 10,
    paddingBottom: 24,
  },
  webFilterSidebar: {
    width: '6cm' as any,
    flexShrink: 0,
    borderRadius: 14,
    borderWidth: 1,
    alignSelf: 'stretch',
    maxHeight: '100%',
  },
  webFilterSidebarContent: {
    padding: 8,
    paddingBottom: 14,
  },
  webSidebarTitle: {
    fontSize: 14,
    fontWeight: '900',
    marginBottom: 6,
  },
  webSidebarSectionTitle: {
    marginTop: 2,
    marginBottom: 8,
    fontSize: 12,
    lineHeight: 16,
  },
  webFilterSectionBlock: {
    paddingTop: 8,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148,163,184,0.18)',
  },
  webResetFiltersBtn: {
    marginTop: 12,
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  webResultsColumn: {
    flex: 1,
    minWidth: 0,
  },
  webResultsTopBar: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 10,
    zIndex: 20,
  },
  webCollectionTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '900',
  },
  webResultCount: {
    fontSize: 13,
    fontWeight: '700',
    color: PRIMARY_DARK,
  },
  webSortWrap: {
    position: 'relative',
    zIndex: 30,
  },
  webSortButton: {
    minWidth: 300,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  webSortText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  webSortMenu: {
    position: 'absolute',
    top: 50,
    right: 0,
    width: 300,
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 10,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.14,
    shadowRadius: 28,
    elevation: 12,
  },
  webSortMenuRow: {
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  webSortMenuText: {
    fontSize: 15,
    fontWeight: '800',
  },
  webSortMenuTextActive: {
    color: PRIMARY,
  },
  webSidebarPriceRow: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 6,
  },
  webSidebarPriceCard: {
    padding: 8,
    borderRadius: 12,
  },
  webSidebarPriceTrackRow: {
    marginBottom: 10,
  },
  webSidebarPriceInput: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  webSidebarPriceField: {
    fontSize: 12,
    lineHeight: 16,
  },
  webSidebarChip: {
    width: '100%',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  webSidebarChipText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  webSidebarAmenityText: {
    fontSize: 12,
    lineHeight: 16,
  },
  filterPanelTitle: {
    fontSize: 15,
    fontWeight: '800',
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  filterBar: { maxHeight: 72 },
  filterBarContent: { paddingHorizontal: 12, gap: 10, paddingBottom: 12 },
  filterChip: {
    minHeight: 48,
    flexDirection: 'row', alignItems: 'center', gap: 8,
    borderRadius: 14, paddingHorizontal: 12, paddingVertical: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(133,194,164,0.45)',
    shadowColor: PRIMARY, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08,
    shadowRadius: 8, elevation: 2,
  },
  filterChipPrimary: { minWidth: 154 },
  filterChipActive: { backgroundColor: 'rgba(133,194,164,0.18)' },
  filterIconBadge: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(133,194,164,0.18)',
  },
  filterTextWrap: { minWidth: 0, flex: 1 },
  filterChipLabel: { fontSize: 11, fontWeight: '700', color: PRIMARY_DARK, marginBottom: 2 },
  filterChipValue: { fontSize: 13, fontWeight: '800', maxWidth: 120 },
  filterCountBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PRIMARY,
  },
  filterCountText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  list: { padding: 16, gap: 12 },
  webListWrap: {
    flex: 1,
  },
  webList: {
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 52,
  },
  skeleton: {
    height: 100, backgroundColor: '#f3f4f6', borderRadius: 16,
    marginBottom: 12,
  },
  emptyText: { textAlign: 'center', color: '#9ca3af', fontSize: 14, marginTop: 24 },
  hotelCard: {
    flexDirection: 'row', borderRadius: 16, overflow: 'hidden',
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06,
    shadowRadius: 8, elevation: 2, marginBottom: 12, borderWidth: 1,
  },
  webHotelCard: {
    minHeight: 150,
    borderRadius: 18,
    marginBottom: 16,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 18,
  },
  hotelImage: { width: 100, height: 100 },
  webHotelImage: { width: 190, height: 150 },
  hotelInfo: { flex: 1, padding: 12 },
  hotelName: { fontSize: 14, fontWeight: '700', color: '#111827', marginBottom: 4 },
  webHotelName: { fontSize: 17, marginBottom: 8 },
  hotelMeta: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 6 },
  hotelRating: { fontSize: 12, fontWeight: '700' },
  hotelReviews: { fontSize: 11, color: '#6b7280', flex: 1 },
  hotelTag: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: 'rgba(133,194,164,0.18)', borderRadius: 6, borderWidth: 1, borderColor: 'rgba(133,194,164,0.35)',
    paddingHorizontal: 6, paddingVertical: 3, alignSelf: 'flex-start', marginBottom: 6,
  },
  hotelTagText: { fontSize: 10, fontWeight: '700', color: PRIMARY_DARK },
  hotelPriceRow: { flexDirection: 'row', alignItems: 'baseline', gap: 4 },
  hotelPrice: { fontSize: 16, fontWeight: '700', color: PRIMARY_DARK },
  webHotelPrice: { fontSize: 20 },
  hotelUnit: { fontSize: 11, color: '#6b7280' },
  // Modals
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
  sheet: {
    borderTopLeftRadius: 24, borderTopRightRadius: 24,
    paddingHorizontal: 16, paddingTop: 12,
  },
  sheetHandle: {
    width: 40, height: 6, borderRadius: 3,
    alignSelf: 'center', marginBottom: 16,
  },
  sheetTitle: { fontSize: 17, fontWeight: '700', color: '#111827', marginBottom: 12 },
  sheetRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#f9fafb',
  },
  sheetRowText: { fontSize: 15, color: '#374151' },
  radioFilled: {
    width: 18, height: 18, borderRadius: 9, backgroundColor: PRIMARY,
    borderWidth: 5, borderColor: 'rgba(133,194,164,0.3)',
  },
  // Filter Modal
  filterModal: { flex: 1 },
  filterHeader: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 16, paddingBottom: 12, borderBottomWidth: 1,
  },
  filterTitle: { fontSize: 17, fontWeight: '700' },
  filterSection: { fontSize: 15, fontWeight: '700', marginBottom: 12, marginTop: 8 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 22 },
  chip: {
    paddingHorizontal: 14, paddingVertical: 8, borderRadius: 99,
    borderWidth: 1,
  },
  chipActive: { backgroundColor: PRIMARY, borderColor: PRIMARY },
  chipText: { fontSize: 13 },
  chipTextActive: { color: '#fff', fontWeight: '600' },
  amenityList: { gap: 10, marginBottom: 8 },
  amenityRow: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 30 },
  checkbox: {
    width: 20, height: 20, borderRadius: 6, borderWidth: 1.5,
    borderColor: 'rgba(133,194,164,0.55)', alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#fff',
  },
  checkboxActive: { backgroundColor: PRIMARY, borderColor: PRIMARY },
  checkboxMark: { color: '#fff', fontSize: 13, fontWeight: '900', lineHeight: 16 },
  amenityText: { fontSize: 14, fontWeight: '500', flex: 1 },
  toggleAmenitiesBtn: { alignSelf: 'flex-start', marginBottom: 18, paddingVertical: 4 },
  toggleAmenitiesText: { color: PRIMARY_DARK, fontSize: 13, fontWeight: '800' },
  priceRangeCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(133,194,164,0.35)',
    padding: 14,
    backgroundColor: '#fff',
  },
  priceTrackRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  priceSlider: {
    height: PRICE_KNOB_SIZE,
    justifyContent: 'center',
    marginBottom: 18,
    position: 'relative',
    marginHorizontal: PRICE_KNOB_SIZE / 2,
  },
  priceTrack: {
    height: 4,
    width: '100%',
    backgroundColor: PRICE_TRACK_INACTIVE,
    borderRadius: 2,
  },
  priceTrackActive: {
    position: 'absolute',
    height: 4,
    borderRadius: 2,
    backgroundColor: PRICE_TRACK_ACTIVE,
  },
  priceKnob: {
    width: PRICE_KNOB_SIZE, height: PRICE_KNOB_SIZE, borderRadius: PRICE_KNOB_SIZE / 2, borderWidth: 2,
    borderColor: PRICE_TRACK_ACTIVE, backgroundColor: '#222728', alignItems: 'center', justifyContent: 'center',
  },
  priceKnobFloating: {
    position: 'absolute',
    top: 0,
    cursor: 'grab' as any,
    zIndex: 4,
  },
  priceKnobMax: { zIndex: 5 },
  priceKnobText: { color: '#f3efe8', fontSize: 20, lineHeight: 22, fontWeight: '800' },
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  priceInput: {
    flex: 1, borderWidth: 1, borderRadius: 12, borderColor: '#d1d5db',
    padding: 12,
  },
  priceLabel: { fontSize: 11, color: '#9ca3af', marginBottom: 4 },
  priceField: { fontSize: 15, fontWeight: '700', padding: 0 },
  priceDash: { color: '#374151', fontSize: 18, fontWeight: '800' },
  filterFooter: {
    flexDirection: 'row', gap: 12, padding: 16, borderTopWidth: 1,
  },
  resetBtn: {
    flex: 1, borderWidth: 1, borderRadius: 12,
    paddingVertical: 14, alignItems: 'center',
  },
  resetBtnText: { fontSize: 15, fontWeight: '600' },
  applyBtn: { flex: 2, backgroundColor: PRIMARY, borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  applyBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },
});
