import { StyleSheet } from 'react-native';
import {
  CUSTOMER_PRIMARY as PRIMARY,
  CUSTOMER_PRIMARY_DARK as PRIMARY_DARK,
} from '@/src/customer/constants/hotelFilters';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  webContainer: {
    overflow: 'hidden',
  },
  gradientBg: {
    position: 'absolute', top: 0, left: 0, right: 0, height: 200,
    backgroundColor: 'rgba(133,194,164,0.3)',
  },
  header: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 16, paddingVertical: 10,
  },
  webHeader: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 18,
  },
  backBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  titleWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  title: { fontSize: 18, fontWeight: '700', textAlign: 'center' },
  // Countdown
  countdownBar: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    paddingHorizontal: 16, paddingVertical: 8,
    backgroundColor: '#fff8e1', marginHorizontal: 16, borderRadius: 12,
    borderWidth: 1, borderColor: '#fde68a', marginBottom: 8,
  },
  webSection: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    marginHorizontal: 0,
    paddingHorizontal: 32,
  },
  countdownLabel: { fontSize: 13, fontWeight: '600', color: '#92400e', flex: 1 },
  countdownTimer: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  timeUnit: {
    backgroundColor: '#111827', borderRadius: 6,
    paddingHorizontal: 8, paddingVertical: 4, minWidth: 32, alignItems: 'center',
  },
  timeNum: { color: '#fff', fontSize: 16, fontWeight: '800', fontVariant: ['tabular-nums'] },
  timeSep: { color: '#111827', fontSize: 18, fontWeight: '800' },
  // Tab bar
  tabBar: {
    flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 8,
  },
  tabBtn: {
    paddingHorizontal: 20, paddingVertical: 8, borderRadius: 99,
    borderWidth: 1,
  },
  tabBtnActive: {
    backgroundColor: PRIMARY, borderColor: PRIMARY,
  },
  tabText: { fontSize: 14, fontWeight: '600' },
  tabTextActive: { color: '#fff' },
  // Filter bar
  filterBar: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    paddingHorizontal: 16, paddingVertical: 8,
    marginHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(133,194,164,0.35)',
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  webFilterBar: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    marginHorizontal: 0,
    paddingHorizontal: 32,
  },
  filterTitleWrap: {
    minWidth: 150,
  },
  filterPanelTitle: { fontSize: 14, fontWeight: '800' },
  filterPanelSubtitle: { fontSize: 11, color: PRIMARY_DARK, fontWeight: '600', marginTop: 2 },
  filterChip: {
    minWidth: 154,
    minHeight: 50,
    flexDirection: 'row', alignItems: 'center', gap: 8,
    borderRadius: 14, paddingHorizontal: 12, paddingVertical: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(133,194,164,0.45)',
    shadowColor: PRIMARY, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08,
    shadowRadius: 8, elevation: 2,
  },
  mobileFilterChip: {
    flex: 1,
    minWidth: 0,
  },
  filterChipActive: { backgroundColor: 'rgba(133,194,164,0.18)' },
  filterIconBadge: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(133,194,164,0.18)',
  },
  filterTextWrap: { minWidth: 0, flex: 1 },
  filterChipLabel: { fontSize: 11, fontWeight: '700', color: PRIMARY_DARK, marginBottom: 2 },
  filterChipValue: { fontSize: 13, fontWeight: '800', maxWidth: 118 },
  filterCountBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PRIMARY,
  },
  filterCountText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  countText: { fontSize: 13, color: PRIMARY_DARK, fontWeight: '700' },
  // List
  list: { padding: 16, paddingTop: 8, gap: 12, paddingBottom: 32 },
  webList: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 32,
    paddingTop: 16,
    paddingBottom: 52,
  },
  skeleton: { height: 110, borderRadius: 16 },
  emptyWrap: { paddingTop: 48, alignItems: 'center' },
  emptyText: { fontSize: 14, color: '#9ca3af' },
  // Hotel card
  hotelCard: {
    flexDirection: 'row', borderRadius: 16, overflow: 'hidden',
    shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06,
    shadowRadius: 8, elevation: 2, borderWidth: 1,
  },
  webHotelCard: {
    minHeight: 132,
  },
  hotelImageWrap: { width: 110, height: 110, position: 'relative' },
  webHotelImageWrap: { width: 156, height: 132 },
  hotelImage: { width: '100%', height: '100%' },
  flashBadge: {
    position: 'absolute', bottom: 6, left: 6,
    backgroundColor: '#eab308', flexDirection: 'row', alignItems: 'center',
    gap: 3, paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6,
  },
  flashBadgeText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  hotBadge: {
    position: 'absolute', bottom: 6, left: 6,
    backgroundColor: '#ff5a5f', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6,
  },
  hotBadgeText: { color: '#fff', fontSize: 10, fontWeight: '700' },
  hotelInfo: { flex: 1, padding: 12, justifyContent: 'flex-start' },
  hotelName: { fontSize: 14, fontWeight: '700', marginBottom: 4, lineHeight: 20 },
  hotelMeta: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 6 },
  hotelRating: { fontSize: 12, fontWeight: '700' },
  hotelReviews: { fontSize: 11, color: '#6b7280', flex: 1 },
  hotelTag: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    backgroundColor: 'rgba(133,194,164,0.18)', borderRadius: 6, borderWidth: 1, borderColor: 'rgba(133,194,164,0.35)',
    paddingHorizontal: 6, paddingVertical: 3, alignSelf: 'flex-start', marginBottom: 6,
  },
  hotelTagText: { fontSize: 10, fontWeight: '700', color: '#599373' },
  hotelPriceBlock: {},
  oldPrice: { fontSize: 11, color: '#9ca3af', textDecorationLine: 'line-through', marginBottom: 2 },
  hotelPriceRow: { flexDirection: 'row', alignItems: 'baseline', gap: 4 },
  hotelPrice: { fontSize: 16, fontWeight: '700', color: PRIMARY_DARK },
  hotelUnit: { fontSize: 11, color: '#6b7280' },
  // Modals
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
  sheet: {
    borderTopLeftRadius: 24, borderTopRightRadius: 24,
    paddingHorizontal: 16, paddingTop: 12,
  },
  sheetHandle: {
    width: 40, height: 6, borderRadius: 3,
    alignSelf: 'center', marginBottom: 16,
  },
  sheetTitle: { fontSize: 17, fontWeight: '700', marginBottom: 12 },
  sheetRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#f9fafb',
  },
  sheetRowText: { fontSize: 15 },
  radioFilled: {
    width: 18, height: 18, borderRadius: 9, backgroundColor: PRIMARY,
    borderWidth: 5, borderColor: 'rgba(133,194,164,0.3)',
  },
  filterModal: { flex: 1 },
  filterHeader: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 16, paddingBottom: 12, borderBottomWidth: 1,
  },
  filterTitle: { fontSize: 17, fontWeight: '700' },
  filterSection: { fontSize: 15, fontWeight: '700', marginBottom: 12, marginTop: 8 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 24 },
  chip: {
    paddingHorizontal: 14, paddingVertical: 8, borderRadius: 99,
    borderWidth: 1,
  },
  chipActive: { backgroundColor: PRIMARY, borderColor: PRIMARY },
  chipText: { fontSize: 13 },
  chipTextActive: { color: '#fff', fontWeight: '600' },
  amenityList: { gap: 10, marginBottom: 8 },
  amenityRow: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 30 },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: 'rgba(133,194,164,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  checkboxActive: { backgroundColor: PRIMARY, borderColor: PRIMARY },
  checkboxMark: { color: '#fff', fontSize: 13, fontWeight: '900', lineHeight: 16 },
  amenityText: { fontSize: 14, fontWeight: '500', flex: 1 },
  toggleAmenitiesBtn: { alignSelf: 'flex-start', marginBottom: 18, paddingVertical: 4 },
  toggleAmenitiesText: { color: PRIMARY_DARK, fontSize: 13, fontWeight: '800' },
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  priceInput: { flex: 1, borderWidth: 1, borderRadius: 12, padding: 12 },
  priceLabel: { fontSize: 11, color: '#9ca3af', marginBottom: 4 },
  priceField: { fontSize: 15 },
  filterFooter: {
    flexDirection: 'row', gap: 12, padding: 16, borderTopWidth: 1,
  },
  resetBtn: {
    flex: 1, borderWidth: 1, borderRadius: 12,
    paddingVertical: 14, alignItems: 'center',
  },
  resetBtnText: { fontSize: 15, fontWeight: '600' },
  applyBtn: { flex: 2, backgroundColor: PRIMARY, borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  applyBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },
});
