import { StyleSheet } from 'react-native';
import {
  ROOM_LIST_PRIMARY,
  ROOM_LIST_PRIMARY_DARK,
  ROOM_LIST_SUCCESS,
} from '@/src/customer/constants/roomList';

export const roomListStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  webContainer: { overflow: 'hidden' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  webHeader: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 18,
  },
  backBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  title: { flex: 1, textAlign: 'center', fontSize: 18, fontWeight: '700', color: '#111827' },
  bookingCard: {
    margin: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(133,194,164,0.38)',
    backgroundColor: '#fbfffd',
    padding: 16,
    gap: 12,
  },
  webPanel: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    marginHorizontal: 0,
    marginTop: 18,
    marginBottom: 12,
    paddingHorizontal: 18,
  },
  bookingRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  bookingType: { flex: 1, fontSize: 16, fontWeight: '700', color: '#374151' },
  changeBtn: { color: ROOM_LIST_PRIMARY_DARK, fontSize: 15, fontWeight: '800' },
  bookingDivider: { height: 1, backgroundColor: 'rgba(133,194,164,0.28)' },
  checkRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  checkLabel: { fontSize: 14, color: '#9ca3af', marginBottom: 4 },
  checkTime: { fontSize: 18, fontWeight: '800', color: '#111827' },
  roomFilterBar: {
    marginHorizontal: 12,
    marginTop: 10,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  webRoomFilterBar: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    marginHorizontal: 0,
    paddingHorizontal: 32,
  },
  roomFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 38,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(133,194,164,0.14)',
  },
  roomFilterChipActive: { backgroundColor: 'rgba(133,194,164,0.24)' },
  roomFilterText: { fontSize: 13, fontWeight: '800' },
  clearFilterText: { color: ROOM_LIST_PRIMARY, fontSize: 13, fontWeight: '800' },
  roomCard: {
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#f3f4f6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  webRoomCard: { alignSelf: 'center', width: '100%' },
  roomImageWrap: { position: 'relative' },
  imgDots: {
    position: 'absolute',
    bottom: 8,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 4,
  },
  imgDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.5)' },
  imgDotActive: { backgroundColor: ROOM_LIST_PRIMARY, width: 14 },
  flashBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: ROOM_LIST_PRIMARY,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  flashBadgeText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  roomBody: { padding: 16 },
  roomName: { fontSize: 22, fontWeight: '800', color: '#111827', marginBottom: 10, lineHeight: 28 },
  roomDescription: { fontSize: 16, lineHeight: 24, fontWeight: '500', marginBottom: 8 },
  roomAmenityLine: { fontSize: 15, lineHeight: 23, fontWeight: '500', marginBottom: 14 },
  roomMeta: { flexDirection: 'row', gap: 14, marginBottom: 10 },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metaTextLg: { fontSize: 14, color: '#6b7280' },
  stockWarning: { color: ROOM_LIST_PRIMARY_DARK, fontSize: 12, fontWeight: '700', marginBottom: 10 },
  roomDivider: { height: 1, marginBottom: 14 },
  bookingActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 14,
  },
  priceBlock: { flex: 1 },
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  salePrice: { fontSize: 23, fontWeight: '900', color: '#111827' },
  discountBadge: { backgroundColor: ROOM_LIST_SUCCESS, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3 },
  discountText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  originalPrice: { fontSize: 13, color: '#9ca3af', textDecorationLine: 'line-through' },
  bookBtn: {
    backgroundColor: ROOM_LIST_PRIMARY,
    borderRadius: 999,
    paddingVertical: 15,
    paddingHorizontal: 28,
    alignItems: 'center',
    shadowColor: ROOM_LIST_PRIMARY,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.24,
    shadowRadius: 8,
    elevation: 5,
  },
  bookBtnText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  benefitsBox: {
    backgroundColor: '#f6f6f6',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
    marginBottom: 16,
  },
  benefitRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  benefitText: { flex: 1, color: '#4b5563', fontSize: 14, lineHeight: 20, fontWeight: '500' },
  paymentRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6 },
  paymentTextSm: { fontSize: 12, color: '#6b7280' },
  policyRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  policyText: { fontSize: 15, color: '#374151', flex: 1, fontWeight: '500' },
  detailLink: { color: ROOM_LIST_PRIMARY_DARK, fontSize: 15, fontWeight: '800' },
  checkIcon: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: ROOM_LIST_SUCCESS,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skeletonCard: { height: 300, backgroundColor: '#f3f4f6', borderRadius: 16 },
  listContent: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 24, gap: 18 },
  webList: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 52,
  },
  emptyText: { textAlign: 'center', color: '#9ca3af', marginTop: 40, fontSize: 14 },
  modalContainer: { flex: 1, backgroundColor: '#fff' },
  webModalContainer: { overflow: 'hidden' },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  webModalHeader: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: 32,
    paddingTop: 18,
    paddingBottom: 18,
  },
  modalTitle: { fontSize: 17, fontWeight: '700', color: '#111827' },
  modalBody: { padding: 16 },
  modalScrollContent: { paddingBottom: 120 },
  webModalScrollContent: { alignItems: 'center', paddingBottom: 64 },
  webModalBody: {
    width: '100%',
    maxWidth: 1180,
    paddingHorizontal: 32,
    paddingTop: 24,
  },
  modalRoomName: { fontSize: 22, fontWeight: '800', color: '#111827', marginBottom: 10 },
  modalSectionTitle: { fontSize: 16, fontWeight: '700', color: '#111827', marginBottom: 10 },
  amenitiesBlock: { marginVertical: 14 },
  amenitiesRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  amenityChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: '#f3f4f6',
  },
  amenityChipText: { fontSize: 12, color: '#374151' },
  bookingDetailCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(133,194,164,0.38)',
    backgroundColor: '#fbfffd',
    padding: 14,
    marginBottom: 20,
    gap: 10,
  },
  bookingDetailRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  bookingDetailType: { fontSize: 14, fontWeight: '600', color: '#374151' },
  checkDetailRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  checkLabelSm: { fontSize: 11, color: '#9ca3af', marginBottom: 2 },
  checkTimeSm: { fontSize: 14, fontWeight: '700', color: '#111827' },
  priceOption: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#f3f4f6',
    padding: 14,
    marginBottom: 12,
    gap: 10,
  },
  priceOptionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  flashTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: ROOM_LIST_PRIMARY,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  flashTagText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  remainingText: { color: ROOM_LIST_PRIMARY, fontSize: 12, fontWeight: '600' },
  priceOptionBody: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  salePriceLg: { fontSize: 20, fontWeight: '800', color: '#111827' },
  originalPriceSm: { fontSize: 12, color: '#9ca3af', textDecorationLine: 'line-through', marginBottom: 4 },
  bookBtnModal: {
    backgroundColor: ROOM_LIST_PRIMARY,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignItems: 'center',
  },
  cancelSection: { paddingTop: 16, borderTopWidth: 1, borderTopColor: '#f9fafb' },
  cancelText: { fontSize: 14, color: '#6b7280', lineHeight: 22 },
});
