import { Platform, StyleSheet } from 'react-native';

const PRIMARY = '#85c2a4';

export const styles = StyleSheet.create({
  container: { paddingHorizontal: 16, paddingBottom: 12 },
  webContainer: {
    paddingHorizontal: 32,
    paddingBottom: 30,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(133,194,164,0.28)',
    zIndex: 160,
    ...(Platform.OS === 'web' ? { position: 'relative' as any } : {}),
  },
  webInner: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    zIndex: 220,
    ...(Platform.OS === 'web' ? { position: 'relative' as any } : {}),
  },
  scrolled: {},
  notScrolled: {
    paddingBottom: 40,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  webTopRow: {
    alignItems: 'center',
    marginBottom: 18,
  },
  brandBlock: {
    flex: 1,
    marginRight: 12,
  },
  brand: { fontSize: 20, fontWeight: '800', letterSpacing: 0 },
  webBrand: { fontSize: 32 },
  subtitle: { fontSize: 12, fontWeight: '500', marginTop: 2 },
  webSubtitle: { fontSize: 14, marginTop: 4 },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
    alignSelf: 'flex-start',
  },
  webLocationRow: {
    backgroundColor: '#fff',
    borderRadius: 99,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(133,194,164,0.45)',
    marginTop: 10,
  },
  location: {
    fontSize: 15,
    fontWeight: '700',
    maxWidth: 160,
  },
  webLocation: {
    maxWidth: 360,
    fontSize: 16,
  },
  actions: { flexDirection: 'row', gap: 8 },
  webActions: {
    position: 'absolute',
    right: 0,
    top: 8,
    alignItems: 'center',
  },
  webScrolledActions: {
    alignItems: 'center',
    marginLeft: 12,
  },
  webAuthActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  webLoginBtn: {
    minHeight: 42,
    borderRadius: 21,
    borderWidth: 1,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  webLoginBtnText: {
    color: PRIMARY,
    fontSize: 14,
    fontWeight: '800',
  },
  webRegisterBtn: {
    minHeight: 42,
    borderRadius: 21,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PRIMARY,
  },
  webRegisterBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  actionBtn: {
    width: 40, height: 40, borderRadius: 20,
    alignItems: 'center', justifyContent: 'center',
  },
  webActionBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1,
    borderColor: 'rgba(133,194,164,0.35)',
  },
  actionBtnSmall: {
    width: 36, height: 36, borderRadius: 18,
    alignItems: 'center', justifyContent: 'center',
  },
  badge: {
    position: 'absolute', top: 6, right: 6,
    width: 8, height: 8, borderRadius: 4, backgroundColor: '#ef4444',
    borderWidth: 1.5, borderColor: '#fff',
  },
  badgeSmall: {
    position: 'absolute', top: 4, right: 4,
    width: 10, height: 10, borderRadius: 5, backgroundColor: '#ef4444',
    borderWidth: 1.5, borderColor: '#fff',
  },
  countBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    backgroundColor: '#ef4444',
    borderWidth: 1.5,
    borderColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  countBadgeSmall: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    backgroundColor: '#ef4444',
    borderWidth: 1.5,
    borderColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  countBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
  },
  webAccountChip: {
    height: 46,
    minWidth: 190,
    maxWidth: 240,
    borderRadius: 23,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingLeft: 7,
    paddingRight: 14,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 4,
  },
  webAccountChipCompact: {
    height: 42,
    minWidth: 178,
  },
  webAccountAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  webAccountAvatarText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  webAccountTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  webAccountName: {
    fontSize: 13,
    fontWeight: '800',
  },
  webAccountRole: {
    marginTop: 1,
    color: PRIMARY,
    fontSize: 11,
    fontWeight: '700',
  },
  webAccountBackdrop: {
    position: 'fixed' as any,
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    zIndex: 150,
  },
  webAccountMenu: {
    position: 'absolute',
    right: 0,
    width: 282,
    borderRadius: 14,
    borderWidth: 1,
    padding: 12,
    zIndex: 220,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
    elevation: 12,
  },
  webAccountMenuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 4,
    marginBottom: 10,
  },
  webAccountMenuAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  webAccountMenuAvatarText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
  },
  webAccountMenuInfo: {
    flex: 1,
    minWidth: 0,
    marginLeft: 12,
  },
  webAccountMenuName: {
    fontSize: 16,
    fontWeight: '900',
  },
  webAccountMenuRole: {
    marginTop: 3,
    color: PRIMARY,
    fontSize: 12,
    fontWeight: '700',
  },
  webMenuDivider: {
    height: 1,
    marginBottom: 12,
  },
  webInfoRow: {
    minHeight: 40,
    borderRadius: 10,
    backgroundColor: '#f8fafc',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 11,
    marginBottom: 8,
  },
  webInfoText: {
    flex: 1,
    color: '#64748b',
    fontSize: 13,
    fontWeight: '600',
  },
  webMenuAction: {
    minHeight: 44,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 11,
  },
  webMenuActionText: {
    color: PRIMARY,
    fontSize: 14,
    fontWeight: '800',
  },
  webMenuLogoutText: {
    color: '#ef4444',
  },
  webMenuNotificationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ef4444',
    marginLeft: 'auto',
  },
  webMenuCountBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    paddingHorizontal: 6,
    backgroundColor: '#ef4444',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
  },
  webMenuCountBadgeText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
  },
  searchRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  webSearchRow: {
    marginTop: 6,
    justifyContent: 'center',
  },
  searchBar: {
    flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8,
    borderRadius: 99, paddingHorizontal: 16, paddingVertical: 12,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05,
    shadowRadius: 4, elevation: 2, borderWidth: 1,
  },
  webSearchBar: {
    maxWidth: 760,
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 15,
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 4,
  },
  searchPlaceholder: { fontSize: 14, fontWeight: '500', flex: 1 },
  webSearchPlaceholder: { fontSize: 15 },
});
