import { StyleSheet } from "react-native";

export const PRIMARY = "#85c2a4";
export const PRIMARY_FILL = "rgba(133,194,164,0.35)";
export const TEXT_DARK = "#25252d";
export const TEXT_MUTED = "#85858d";
export const BORDER = "#ededf1";
export const SURFACE = "#ffffff";
export const PAGE_BG = "#f7f7f8";
export const SUCCESS = PRIMARY;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  webContainer: {
    width: "100%",
    maxWidth: 1180,
    alignSelf: "center",
    overflow: "visible",
  },
  header: {
    height: 96,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: SURFACE,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f2",
    paddingHorizontal: 22,
  },
  webHeader: {
    height: 82,
    marginTop: 24,
    marginHorizontal: 32,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: BORDER,
    paddingHorizontal: 24,
  },
  headerIconBtn: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    flex: 1,
    color: TEXT_DARK,
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  headerSpacer: {
    width: 46,
  },
  scrollContent: {
    backgroundColor: SURFACE,
  },
  webScrollContent: {
    minHeight: 760,
    paddingHorizontal: 32,
    paddingTop: 24,
    paddingBottom: 220,
  },
  section: {
    backgroundColor: SURFACE,
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  webSection: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    marginBottom: 18,
    paddingHorizontal: 28,
    paddingVertical: 26,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.04,
    shadowRadius: 18,
    elevation: 2,
  },
  sectionTitle: {
    color: TEXT_DARK,
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 16,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  editText: {
    color: PRIMARY,
    fontSize: 15,
    fontWeight: "800",
  },
  choiceRow: {
    flexDirection: "row",
    gap: 14,
  },
  webChoiceRow: {
    gap: 18,
  },
  roomImage: {
    width: 142,
    height: 126,
    borderRadius: 12,
  },
  webRoomImage: {
    width: 190,
    height: 136,
    borderRadius: 16,
  },
  choiceInfo: {
    flex: 1,
    minWidth: 0,
    paddingTop: 4,
  },
  hotelName: {
    color: TEXT_DARK,
    fontSize: 15,
    lineHeight: 21,
  },
  roomName: {
    color: TEXT_DARK,
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 24,
    textTransform: "uppercase",
  },
  addressText: {
    color: TEXT_DARK,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  thinDivider: {
    height: 1,
    backgroundColor: BORDER,
    marginTop: 24,
    marginBottom: 24,
  },
  timeRow: {
    flexDirection: "row",
    gap: 14,
  },
  webTimeRow: {
    gap: 18,
  },
  durationCard: {
    width: 142,
    minHeight: 150,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PRIMARY,
  },
  webDurationCard: {
    width: 180,
    minHeight: 156,
    borderRadius: 18,
  },
  clockCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: SURFACE,
    marginBottom: 24,
  },
  durationText: {
    color: SURFACE,
    fontSize: 18,
    fontWeight: "900",
  },
  timeCard: {
    flex: 1,
    minHeight: 150,
    borderRadius: 14,
    backgroundColor: "#f7f7f8",
    paddingHorizontal: 18,
    paddingVertical: 16,
    justifyContent: "center",
  },
  webTimeCard: {
    minHeight: 156,
    borderRadius: 18,
    paddingHorizontal: 24,
  },
  timeLabel: {
    color: TEXT_MUTED,
    fontSize: 14,
    marginBottom: 6,
  },
  checkoutLabel: {
    marginTop: 18,
  },
  timeValue: {
    color: TEXT_DARK,
    fontSize: 17,
    fontWeight: "900",
  },
  band: {
    height: 14,
    backgroundColor: PAGE_BG,
  },
  webBand: {
    display: "none",
  },
  infoLine: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
  },
  infoLabel: {
    color: TEXT_DARK,
    fontSize: 16,
  },
  infoValue: {
    flex: 1,
    color: TEXT_DARK,
    fontSize: 16,
    fontWeight: "800",
    textAlign: "right",
  },
  actionRow: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowLabelWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    flexShrink: 1,
  },
  actionTitle: {
    color: TEXT_DARK,
    fontSize: 18,
    fontWeight: "900",
  },
  paymentLine: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: BORDER,
    gap: 18,
  },
  paymentLineTop: {
    marginTop: 8,
  },
  paymentLineSeparator: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: BORDER,
  },
  paymentLabel: {
    color: TEXT_DARK,
    fontSize: 16,
  },
  paymentValue: {
    color: TEXT_DARK,
    fontSize: 16,
  },
  totalTitle: {
    color: TEXT_DARK,
    fontSize: 18,
    fontWeight: "900",
  },
  policyText: {
    color: TEXT_DARK,
    fontSize: 15,
    lineHeight: 23,
    marginBottom: 12,
  },
  policyStrong: {
    fontWeight: "900",
  },
  inlineLink: {
    color: PRIMARY,
    fontWeight: "900",
    textDecorationLine: "underline",
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: SURFACE,
    borderTopWidth: 1,
    borderTopColor: "#f1f1f3",
    paddingHorizontal: 24,
    paddingTop: 18,
  },
  webBottomBar: {
    left: 32,
    right: 32,
    bottom: 24,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    paddingHorizontal: 24,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 4,
  },
  paymentMethodRow: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  paymentMethodTextBlock: {
    flexShrink: 1,
  },
  paymentMethodText: {
    color: TEXT_DARK,
    fontSize: 16,
    fontWeight: "700",
  },
  paymentMethodSubText: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 3,
  },
  bottomDivider: {
    height: 1,
    backgroundColor: BORDER,
    marginTop: 12,
    marginBottom: 12,
  },
  bottomSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 18,
  },
  bottomLabel: {
    color: TEXT_MUTED,
    fontSize: 14,
    marginBottom: 4,
  },
  bottomPrice: {
    color: TEXT_DARK,
    fontSize: 24,
    fontWeight: "900",
  },
  bookButton: {
    width: 184,
    minHeight: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PRIMARY,
  },
  bookButtonDisabled: {
    opacity: 0.6,
  },
  bookButtonText: {
    color: SURFACE,
    fontSize: 16,
    fontWeight: "800",
  },
  methodOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15,23,42,0.38)",
  },
  methodSheet: {
    width: "100%",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: SURFACE,
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 26,
  },
  webMethodSheet: {
    width: 520,
    alignSelf: "center",
    borderRadius: 20,
    marginBottom: 42,
    borderWidth: 1,
    borderColor: BORDER,
  },
  methodSheetHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 18,
  },
  methodSheetTitle: {
    color: TEXT_DARK,
    fontSize: 20,
    fontWeight: "900",
  },
  methodSheetSubtitle: {
    color: TEXT_MUTED,
    fontSize: 14,
    fontWeight: "600",
    marginTop: 4,
  },
  methodCloseBtn: {
    minHeight: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    backgroundColor: "#f3f4f6",
  },
  methodCloseText: {
    color: TEXT_DARK,
    fontSize: 13,
    fontWeight: "800",
  },
  methodList: {
    gap: 12,
    marginBottom: 18,
  },
  methodOption: {
    minHeight: 82,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: BORDER,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: SURFACE,
  },
  methodOptionSelected: {
    borderColor: PRIMARY,
    backgroundColor: "rgba(133,194,164,0.08)",
  },
  methodOptionDisabled: {
    opacity: 0.58,
  },
  methodIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(133,194,164,0.12)",
  },
  methodIconWrapSelected: {
    backgroundColor: PRIMARY,
  },
  methodInfo: {
    flex: 1,
    minWidth: 0,
  },
  methodTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  methodTitle: {
    flexShrink: 1,
    color: TEXT_DARK,
    fontSize: 15,
    fontWeight: "900",
  },
  methodDescription: {
    color: TEXT_MUTED,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
  },
  methodTextDisabled: {
    color: "#737373",
  },
  methodBadge: {
    color: "#737373",
    fontSize: 11,
    fontWeight: "900",
    backgroundColor: "#eeeeee",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  methodContinueBtn: {
    width: "100%",
    minHeight: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PRIMARY,
  },
  methodContinueBtnDisabled: {
    opacity: 0.45,
  },
  methodContinueText: {
    color: SURFACE,
    fontSize: 16,
    fontWeight: "900",
  },
  qrScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingVertical: 24,
    backgroundColor: SURFACE,
  },
  webQrScrollContent: {
    alignItems: "center",
    backgroundColor: PAGE_BG,
    paddingTop: 28,
  },
  qrPanel: {
    width: "100%",
    alignItems: "center",
  },
  webQrPanel: {
    maxWidth: 520,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: SURFACE,
    padding: 28,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.06,
    shadowRadius: 22,
    elevation: 3,
  },
  qrTitle: {
    color: TEXT_DARK,
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 8,
    textAlign: "center",
  },
  qrSubtitle: {
    color: TEXT_MUTED,
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 20,
    textAlign: "center",
  },
  countdownBox: {
    width: "100%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(133,194,164,0.35)",
    backgroundColor: "rgba(133,194,164,0.1)",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 16,
    marginBottom: 18,
  },
  countdownBoxGrace: {
    borderColor: "rgba(245,158,11,0.35)",
    backgroundColor: "rgba(245,158,11,0.1)",
  },
  countdownBoxExpired: {
    borderColor: "rgba(220,38,38,0.24)",
    backgroundColor: "rgba(220,38,38,0.08)",
  },
  countdownTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  countdownTitle: {
    color: TEXT_DARK,
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 4,
  },
  countdownTitleExpired: {
    color: "#991b1b",
  },
  countdownValue: {
    color: PRIMARY,
    fontSize: 30,
    fontWeight: "900",
    marginBottom: 5,
  },
  countdownValueGrace: {
    color: "#b45309",
  },
  countdownValueExpired: {
    color: "#dc2626",
    fontSize: 17,
  },
  countdownDescription: {
    color: TEXT_MUTED,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
  },
  qrImageWrap: {
    width: 292,
    maxWidth: "100%",
    aspectRatio: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: SURFACE,
    marginBottom: 22,
    overflow: "hidden",
  },
  qrImage: {
    width: "100%",
    height: "100%",
  },
  qrImageExpired: {
    opacity: 0.35,
  },
  transferBox: {
    width: "100%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: BORDER,
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  transferLine: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
  },
  transferLabel: {
    color: TEXT_MUTED,
    fontSize: 14,
    fontWeight: "700",
  },
  transferValue: {
    flex: 1,
    color: TEXT_DARK,
    fontSize: 15,
    fontWeight: "900",
    textAlign: "right",
  },
  paymentRulesBox: {
    width: "100%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(133,194,164,0.35)",
    backgroundColor: "rgba(133,194,164,0.09)",
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
  },
  paymentRulesTitle: {
    color: TEXT_DARK,
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 12,
  },
  paymentRuleLine: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 10,
  },
  paymentRuleIndex: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PRIMARY,
    marginTop: 1,
  },
  paymentRuleIndexText: {
    color: SURFACE,
    fontSize: 12,
    fontWeight: "900",
  },
  paymentRuleText: {
    flex: 1,
    color: TEXT_DARK,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  supportBox: {
    width: "100%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: BORDER,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,
  },
  supportTitle: {
    color: TEXT_DARK,
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 10,
  },
  supportInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  supportInfoText: {
    flex: 1,
    color: TEXT_DARK,
    fontSize: 14,
    fontWeight: "700",
  },
  supportActionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 6,
  },
  supportActionBtn: {
    flex: 1,
    minHeight: 42,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(133,194,164,0.45)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(133,194,164,0.08)",
  },
  supportActionText: {
    color: PRIMARY,
    fontSize: 14,
    fontWeight: "900",
  },
  waitingBox: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginBottom: 14,
  },
  waitingText: {
    color: TEXT_MUTED,
    fontSize: 14,
    fontWeight: "700",
  },
  paymentErrorText: {
    color: "#dc2626",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 12,
  },
  successContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
    backgroundColor: SURFACE,
  },
  webSuccessContainer: {
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
  },
  successTitle: {
    color: TEXT_DARK,
    fontSize: 22,
    fontWeight: "900",
    marginTop: 22,
    marginBottom: 10,
  },
  successText: {
    color: TEXT_MUTED,
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
    marginBottom: 28,
  },
  successPrimaryBtn: {
    width: "100%",
    minHeight: 54,
    borderRadius: 16,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PRIMARY,
    marginBottom: 12,
  },
  complaintBtn: {
    width: "100%",
    minHeight: 54,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(133,194,164,0.45)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: SURFACE,
    marginBottom: 12,
  },
  complaintBtnText: {
    color: PRIMARY,
    fontSize: 16,
    fontWeight: "900",
  },
  successSecondaryBtn: {
    width: "100%",
    minHeight: 54,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: PRIMARY,
    marginBottom: 12,
    opacity: 0.82,
  },
  successPrimaryText: {
    color: SURFACE,
    fontSize: 16,
    fontWeight: "800",
  },
  successGhostBtn: {
    width: "100%",
    minHeight: 54,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  successGhostText: {
    fontSize: 16,
    fontWeight: "700",
  },
});
